// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRS9Kqe0nWGcOf1kltFkJjRBzCeXi_e8k',
    appId: '1:674515960796:web:df0f3c683e9a1786248519',
    messagingSenderId: '674515960796',
    projectId: 'contacts-app-3c44f',
    authDomain: 'contacts-app-3c44f.firebaseapp.com',
    storageBucket: 'contacts-app-3c44f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpVL3RcCZMvNOjP5j__ASb5o2wykjEfGs',
    appId: '1:674515960796:android:f4ad8121456a2331248519',
    messagingSenderId: '674515960796',
    projectId: 'contacts-app-3c44f',
    storageBucket: 'contacts-app-3c44f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTZHUgvpa3Uo1OicAWslLl2UG6eGJzE5M',
    appId: '1:674515960796:ios:959afdc05239afad248519',
    messagingSenderId: '674515960796',
    projectId: 'contacts-app-3c44f',
    storageBucket: 'contacts-app-3c44f.appspot.com',
    iosBundleId: 'com.example.cBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTZHUgvpa3Uo1OicAWslLl2UG6eGJzE5M',
    appId: '1:674515960796:ios:959afdc05239afad248519',
    messagingSenderId: '674515960796',
    projectId: 'contacts-app-3c44f',
    storageBucket: 'contacts-app-3c44f.appspot.com',
    iosBundleId: 'com.example.cBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRS9Kqe0nWGcOf1kltFkJjRBzCeXi_e8k',
    appId: '1:674515960796:web:2fe67b785b9ece9a248519',
    messagingSenderId: '674515960796',
    projectId: 'contacts-app-3c44f',
    authDomain: 'contacts-app-3c44f.firebaseapp.com',
    storageBucket: 'contacts-app-3c44f.appspot.com',
  );
}
